server {
    listen 80;
    server_name localhost;

    client_max_body_size 10M;

    # 1. Servir la aplicación Angular
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        # Esto es vital para que funcione el enrutamiento interno de Angular
        try_files $uri $uri/ /index.html; 
    }

    # 2. Proxy inverso para la API (Node.js)
    location /api/ {
        # 'backend' es el nombre del servicio en tu compose.yaml
        proxy_pass http://backend:3000/api/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    # 3. Proxy para imágenes subidas al backend
    location /uploads/ {
        proxy_pass http://backend:3000/uploads/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
    }
}
