services:
  # 1. Base de Datos
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: adoptalia_db
      MYSQL_USER: adoptalia_user
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./db/mysql:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d

  # 2. Backend (Node.js)
  backend:
    build: ./backend
    container_name: node-backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_USER=adoptalia_user
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_NAME=adoptalia_db
      - PORT=3000
    depends_on:
      - db

  # 3. Frontend (Angular)
  frontend:
    build: ./frontend
    container_name: angular-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

  # 4. Gestor de base de datos 
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=db
      - PMA_USER=adoptalia_user
      - PMA_PASSWORD=${MYSQL_PASSWORD}
    depends_on:
      - db
